version: '3.9'
services:
  database:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: edulivre
      MYSQL_USER: my_user
      MY_PASSWORD: user_password
    ports:
      - "3000:3000"
    networks:
      - app-network
    # volumes:
    #  - db_data:/var/lib/mysql
  backend:
    build:
      context: ../EstacaoDoFornoBack
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ../EstacaoDoFornoFront
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

    network:
      - app-network